### ISSUE TITLE
参数为null的问题

### ISSUE THREAD

**Issue by gxcsoccer** [node-modules/hessian.js#40]
我这边遇到这样的问题，一个方法有2个参数，类型都是：java.lang.Long。其中一个可以传null。

如果这样写：
```js
var args = [
        java('java.lang.Long', id),
        null
];
```
后端反序列化时会报错，因为无法知道第二个参数的类型。

结合之前遇到的问题，如果一个对象，我要传null值，不能写成`java('xxx.xxx.xxx', null)`，而要直接写null。这样感觉很奇怪

我建议：

1. `java('xxx.xxx.xx', null)`  序列化成 null
2. `java('xxx.xxx.xxx', {})`  这样序列化成默认对象

不知道我描述清楚没有

**Comment by dead-horse** [comment]
js-to-java 的问题？

**Comment by gxcsoccer** [comment]
应该算是hessian.js的问题，hsf request在拿methodArgs的时候，如果参数是null, 参数的签名就是"null"， 服务端反序列化的时候，就会报： “java.lang.ClassNotFoundException” 异常

**Comment by fengmk2** [comment]
感觉这个问题无法自动化统一解决

**Comment by gxcsoccer** [comment]
@fengmk2 我说的那个方案有什么问题吗，昨天晚上状态不好，今天我提个PR

**Comment by fengmk2** [comment]
long的id传递为null也序列化成null？
