### ISSUE TITLE
讨论: Long 类型是否需要默认转换成 String

### ISSUE THREAD

**Issue by zhangyuheng** [node-modules/hessian.js#55]
目前，hessian.js 对 Long 类型转换是智能的：
https://github.com/node-modules/hessian.js/blob/master/lib/utils.js#L41-L52

```javascript
exports.handleLong = function (val) {
  var notSafeInt = val.high > MAX_INT_HIGH ||       // bigger than 2^54
    (val.high === MAX_INT_HIGH && val.low > 0) ||   // between 2^53 ~ 2^54
    val.high < -1 * MAX_INT_HIGH ||                 // smaller than -2^54
    (val.high === -1 * MAX_INT_HIGH && val.low < 0);// between -2^54 ~ -2^53

  if (notSafeInt) {
    debug('[hessian.js Warning] Read a not safe long, translate it to string');
    return val.toString();
  }
  return val.toNumber();
};
```

如果开发者需要用到转换后的值，并把它作为参数，而且这又恰好一个安全的整数的话，那么**会在 js-to-java 里得到安全警告**（如 decode 得到一个 3632295333 为 toNumber()）：
https://github.com/node-modules/js-to-java/blob/master/index.js#L99-L104
```javascript
function safeLong(val) {
  if (process.env.NODE_ENV !== 'production' && typeof val !== 'string') {
    console.trace('Do not be nervous, this is just a warning! Long value: ' + val + ' is a Number, Use String type will be more safe!');
  }
  return val;
}
```

所以，如果默认转换成 String，可以不用关心是使用它时，是用了数字类型还是字符串类型，当然，**这会失去保留转换成 Number 的特性**。（如果不在 hessian.js 里改，那么还可以在 js-to-java 里修改安全判断规则和 hessian.js 一致）

**Comment by fengmk2** [comment]
@coolme200 js-to-java 里面可以加上是否安全number 的判断

**Comment by fengmk2** [comment]
@zhangyuheng 或者你去尝试给 js-to-java 贡献一个 pr？

**Comment by zhangyuheng** [comment]
Have a try

**Comment by zhangyuheng** [comment]
现在直接给使用者提示是合适的，不用修改

**Comment by Akimotorakiyu** [comment]
@zhangyuheng 不合适。至少应该提供一个参数来控制这个行为。
1. 塞进去什么，就返回什么才符合预期。现在塞一个数字进去，返回可能是一个字符串，完全不符合序列化和反序列化应该的预期。 
2. 数字精度，是数字标准的问题，是业务的问题，不是序列化和反序列化应该额外处理的问题。用户塞进来的是这个数，就返回这个数就好，用户既然塞了，就说明这个数是符合预期的。现在业务方还得在所有数字的地方，再转一遍数字。
3. 心智负担重，所有使用了这这个地方都得操心处理。而且一般得很大的数据量才可能发现这个问题，隐式的问题还很难排。
