### ISSUE TITLE
isSafe(long) 的判断有点不符合规范

### ISSUE THREAD

**Issue by fool2fish** [node-modules/hessian.js#56]
源码实现见：https://github.com/node-modules/hessian.js/blob/master/lib/utils.js#L42

es6 的规范：https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isSafeInteger

两者的区别在于： 源码中认为 `2^53` 是安全的，但 es6 的规范认为是不安全的

实际上 `2^53` 在 js 中是可以准确表示的，因为这个根据双精度浮点数规范，是落在最小空隙为 2 的区间里，但刚好是可以准确表示的那个数（2^53+1 就不可以准确表示，显示值和 2^53 一样），于是就变成实际上安全，但却不合规范

呃，要不要改就看作者心情了

**Comment by fengmk2** [comment]
改

**Comment by fool2fish** [comment]
好咯，稍后我发个 pr 上来

**Comment by dead-horse** [comment]
作者心情不错..
