### ISSUE TITLE
writeDate上下限检查错误

### ISSUE THREAD

**Issue by xusiyuan841028** [node-modules/hessian.js#68]
[错误代码](https://github.com/node-modules/hessian.js/blob/master/lib/v2/encoder.js#L260):

``` javascript
proto.writeDate = function (milliEpoch) {
  if (milliEpoch instanceof Date) {
    milliEpoch = milliEpoch.getTime();
  }

  this._assertType('writeDate', 'number', milliEpoch);

  if ((milliEpoch % 60000) === 0) {
    // compact date
    var minutes = milliEpoch / 60000;
    if ((minutes >> 31) === 0 || (minutes >> 31)  === -1) {
      this.byteBuffer
        .put(0x4b)
        .putInt32(minutes);
      return this;
    }
  }
```

[原因](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_Operators#Bitwise_shift_operators):
**_`if ((minutes >> 31) === 0 || (minutes >> 31)  === -1) {`**_这行代码是为了防止分钟超过32位有符号整数上下限，但JavaScript中的位移操作符会预先把`minutes`转换成32位整数:

> Shift operators convert their operands to 32-bit integers in big-endian order and return a result of the same type as the left operand. The right operand should be less than 32, but if not only the low five bits will be used.

所以这个校验是无效的。请参考[Node.js中buffer.js检查整数上下限的代码](https://github.com/nodejs/node/blob/master/lib/buffer.js#L1220)，修改如下

``` javascript
proto.writeDate = function (milliEpoch) {
  if (milliEpoch instanceof Date) {
    milliEpoch = milliEpoch.getTime();
  }

  this._assertType('writeDate', 'number', milliEpoch);

  if ((milliEpoch % 60000) === 0) {
    // compact date
    var minutes = milliEpoch / 60000;
    // FIXED
    if (minutes >= -0x80000000 && minutes <= 0x7fffffff) {
      this.byteBuffer
        .put(0x4b)
        .putInt32(minutes);
      return this;
    }
  }
```

**Comment by fengmk2** [comment]
@xusiyuan841028 Please help us to fix this.

**Comment by xusiyuan841028** [comment]
@fengmk2 我在egg上提issue了，你懂的。。。。。。

**Comment by dead-horse** [comment]
@xusiyuan841028 既然已经找出了 bug 在哪里，提一个 PR 修复？

**Comment by xusiyuan841028** [comment]
@dead-horse OK!
